### ISSUE TITLE
rates confusion

### ISSUE THREAD

**Issue by gorham3690** [harmscho/NuTauSim#1]
Hi Harm,
  I started playing with your code, it is well written and clear. 
I am trying to understand the steep event in ANITA (of course) and wanted to see what happens if I suppress the cross section. So I just did a simple hack in your code to lower the whole cross section (cc and nc) by a factor of 10. Then I ran it for 1e18 eV and zenith angle 124.5 (34.5 deg emergence angle, a bit steeper than our event but just an arbitrary choice), and printed out the number of neutrino interaction lengths, about 2.3 in this case with the suppressed cross section.  For 100K trials, I got around 33 surviving taus.
  To compare this, I went back to the SM cross section, and then found an angle (95  deg zenith or 5 deg emergence angle) where the 1e18eV  neutrino attenuation was very similar, about 2.3 interaction lengths. When I ran 100K events I got 415 surviving taus, a factor of 13 more. The neutrino interaction length should not be a factor in comparing these, so its just the tau survival that is vastly improved at the skimming angle.  The resulting energies of the two groups of taus was very similar overall.
  I don't understand how that can be right. I used 4km of ice depth, so the 5 deg taus have to go through 45 km of ice if they are generated near the bottom, that is just too far. So they almost all must be generated in the ice. The ones emerging at 34.5 deg go through 7km of ice, so they can get out from both ice and rock. Now of course the energy loss in the rock is more, but still it does not look like the difference should be so large, more than an order of magnitude.
 Any ideas?
Peter

**Comment by harmscho** [comment]
See below discussion by email: 
----------------------------------

(Enrique and Jaime)

Dear Peter, 

Hi from Santiago!

I think you can understand this as due to the change in the cross section. 
The relevant interaction volume/mass for the tau to exit is basically fixed by the tau range 
and that should not be that different in both cases, as you are pointing out. 
The interaction rate in a given mass however will decrease roughly 
by a factor of ten when you reduce the cross section. 
Whether we use volume or mass will alter the numbers but not the argument because 
differences should be well below the ratio of the densities (3 at most). 
[At 1 EeV tau energy loss plays an important role in the tau range (which is smaller the 
tau decay length), say of order 30 km (I am guessing here but the actual number is not 
that relevant). The range is thus not governed by distance alone (decay) nor by grammage 
alone (energy loss), but it is a combination of the two]. 

You can also consider the distribution of the neutrino interactions along the chords. 
You are basically fixing the interaction probability, so attenuation of the neutrino flux will be similar. 
The distribution of interactions along the corresponding chords of Earth will be similar when plotted 
in terms of relative fraction of the chord traveled. 
The number of interactions in the latter and relevant part of the chord (of size fixed by a 
combination of distance and grammage which has some dependence on zenith angle -below a factor of 3-) 
will be related to the corresponding fraction of chord, much smaller if the chord is larger.  

I hope I made myself clear, it is often difficult to transmit these ides by words without graphs... 

Best regards,

Enrique and Jaime


---------------------

(Andres)

Hi Peter,
I agree with Enrique and Jaime’s interpretation. The tau lepton decay range (energy loss combined with decay) at 10^18 eV is ~10 km for rock and ~20 km for ice. We did not make this figure in our paper but you can find it here (http://inspirehep.net/record/619608/plots).  For the 5 deg emergence angle, 4 km ice thickness, (~100 km chord length), with unmodified cross-section, any tau-lepton producing interaction within ~20 km of the surface has a decent probability of escape.   In the 35 deg elevation angle, 4 km ice thickness (~700 km chord length), only interactions ~10 km from the surface have a decent chance of escape. With 2.3 interaction lengths, the nu_tau interaction can pretty much happen anywhere in that chord and regeneration should not be a significant effect. So I can crudely estimate that the fraction of interactions that yield a tau lepton escape is (700 km / 10 km) / (100 km / 20 km) ~ 14. The ratio of exiting taus you got is 415/33 ~ 12.6, which is pretty close to the crude estimate.


--------------------------

(Peter)

Yes thanks guys, of course I forgot that when you dial down the cross section, you also dial down the rate of interactions per km, so that makes sense.
When I run with the 10x suppressed cross section for 4km ice in both cases, I get about 92 events at 95 degrees  and around 38 for the -34.5 deg case, so its roughly consistent with your estimates. What is still a bit hard to understand though, when I run with the suppressed cross section at 95 degrees with no ice at all, I get more like 150 events, compared to the 92 with 4km of ice.
What is the physics reason for that?
cheers,
Peter

------------------------------

(Andres)

The number of interactions depends on the density of the material. With rock only, you benefit from the higher density 2.65 g/cm^3 compares to 0.92 g/cm^3 of ice. So you expect to have ~2.9 times the number of interaction in rock only. The tau decay range is about twice as long in ice compared to rock so you get a factor of 2 more usable track-length in ice, so that factor of 2.9 benefit or rock gets divided by 2 when you take that into account. The expected result is ~1.45 times better in rock than ice. Your event ratio is ~1.6, which is within the Poisson fluctuations of the crude estimate.


------------------------------
(Peter)

OK sounds plausible
